// SPDX-License-Identifier: Apache-2.0
// Generated from src-tauri by `pnpm bindings`. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns the application version, platform, and interface language. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Called by the frontend once its first screen has rendered. */
	shellReady: () => __TAURI_INVOKE<void>("shell_ready"),
	/**  Returns which inventory areas have content. */
	inventoryAreas: () => typedError<Areas, Failure>(__TAURI_INVOKE("inventory_areas")),
	/**  Lists groups with live-host counts. */
	inventoryGroups: () => typedError<GroupSummary[], Failure>(__TAURI_INVOKE("inventory_groups")),
	/**  Lists hosts from a source, filtered by the optional query. */
	inventoryHosts: (source: HostSource, query: string) => typedError<HostSummary[], Failure>(__TAURI_INVOKE("inventory_hosts", { source, query })),
	/**  Lists the newest live entries in the device-local Recent session history. */
	inventoryRecentSessions: () => typedError<RecentSession[], Failure>(__TAURI_INVOKE("inventory_recent_sessions")),
	/**  Records that a real connection owner opened a device-local session. */
	sessionOpen: (profileId: string, kind: RecentSessionKind) => typedError<RecentSession, SessionError>(__TAURI_INVOKE("session_open", { profileId, kind })),
	/**  Records the outcome reported by a real connection owner. */
	sessionClose: (sessionId: string, outcome: RecentSessionOutcome) => typedError<null, SessionError>(__TAURI_INVOKE("session_close", { sessionId, outcome })),
	/**
	 *  Requests a reconnect through the connection engine.
	 *
	 *  The engine is not part of this client build yet, so the core returns an
	 *  explicit boundary error and does not create a new session or claim success.
	 */
	sessionReconnect: (sessionId: string) => typedError<null, SessionError>(__TAURI_INVOKE("session_reconnect", { sessionId })),
	/**  Forgets one ended session and its saved local scrollback. */
	sessionForget: (sessionId: string) => typedError<null, SessionError>(__TAURI_INVOKE("session_forget", { sessionId })),
	/**  Reads one host and its logins. */
	inventoryHost: (id: string) => typedError<({
	/**  Plain-text notes. */
	notes: string | null,
	/**  All logins for this host. */
	logins: LoginSummary[],
}) & (HostSummary) | null, Failure>(__TAURI_INVOKE("inventory_host", { id })),
	/**  Creates a host, credential, and default login as one operation. */
	inventoryAddHost: (host: NewHost) => typedError<HostDetails, AddHostError>(__TAURI_INVOKE("inventory_add_host", { host })),
	/**  Changes a host's favorite marker. */
	inventorySetFavorite: (id: string, favorite: boolean) => typedError<null, Failure>(__TAURI_INVOKE("inventory_set_favorite", { id, favorite })),
	/**  Updates host metadata, tags, and group memberships in one core operation. */
	inventoryUpdateHost: (id: string, host: EditHost) => typedError<HostDetails, EditHostError>(__TAURI_INVOKE("inventory_update_host", { id, host })),
	/**  Creates a host group. */
	inventoryCreateGroup: (group: GroupInput) => typedError<GroupSummary, GroupError>(__TAURI_INVOKE("inventory_create_group", { group })),
	/**  Updates a host group name and parent. */
	inventoryUpdateGroup: (id: string, group: GroupInput) => typedError<GroupSummary, GroupError>(__TAURI_INVOKE("inventory_update_group", { id, group })),
	/**  Lists independent access profiles with redacted references. */
	inventoryAccessProfiles: () => typedError<AccessProfileSummary[], ObjectEditError>(__TAURI_INVOKE("inventory_access_profiles")),
	/**  Creates an independent access profile. */
	inventoryCreateAccessProfile: (profile: AccessProfileInput) => typedError<AccessProfileSummary, ObjectEditError>(__TAURI_INVOKE("inventory_create_access_profile", { profile })),
	/**  Replaces an independent access profile. */
	inventoryUpdateAccessProfile: (id: string, profile: AccessProfileInput) => typedError<AccessProfileSummary, ObjectEditError>(__TAURI_INVOKE("inventory_update_access_profile", { id, profile })),
	/**  Deletes an independent access profile after reference checks. */
	inventoryDeleteAccessProfile: (id: string) => typedError<null, ObjectEditError>(__TAURI_INVOKE("inventory_delete_access_profile", { id })),
	/**  Restores the tombstoned host that leaves an access profile orphaned. */
	inventoryRestoreOrphanedHost: (id: string) => typedError<null, ObjectEditError>(__TAURI_INVOKE("inventory_restore_orphaned_host", { id })),
	/**  Restores a tombstoned user-owned object that another live object references. */
	inventoryRestoreOrphanedObject: (id: string) => typedError<null, ObjectEditError>(__TAURI_INVOKE("inventory_restore_orphaned_object", { id })),
	/**  Lists redacted independent credentials. */
	inventoryCredentials: () => typedError<CredentialSummary[], ObjectEditError>(__TAURI_INVOKE("inventory_credentials")),
	/**  Creates a redacted independent credential. */
	inventoryCreateCredential: (credential: CredentialInput) => typedError<CredentialSummary, ObjectEditError>(__TAURI_INVOKE("inventory_create_credential", { credential })),
	/**  Replaces a redacted independent credential. */
	inventoryUpdateCredential: (id: string, credential: CredentialInput) => typedError<CredentialSummary, ObjectEditError>(__TAURI_INVOKE("inventory_update_credential", { id, credential })),
	/**  Deletes an independent credential after reference checks. */
	inventoryDeleteCredential: (id: string) => typedError<null, ObjectEditError>(__TAURI_INVOKE("inventory_delete_credential", { id })),
	/**  Lists independent routes. */
	inventoryRoutes: () => typedError<RouteSummary[], ObjectEditError>(__TAURI_INVOKE("inventory_routes")),
	/**  Creates an independent route. */
	inventoryCreateRoute: (route: RouteInput) => typedError<RouteSummary, ObjectEditError>(__TAURI_INVOKE("inventory_create_route", { route })),
	/**  Replaces an independent route. */
	inventoryUpdateRoute: (id: string, route: RouteInput) => typedError<RouteSummary, ObjectEditError>(__TAURI_INVOKE("inventory_update_route", { id, route })),
	/**  Deletes an independent route after reference checks. */
	inventoryDeleteRoute: (id: string) => typedError<null, ObjectEditError>(__TAURI_INVOKE("inventory_delete_route", { id })),
	/**  Tombstones a host and returns a short-lived undo token. */
	inventoryDeleteHost: (id: string) => typedError<Deletion, Failure>(__TAURI_INVOKE("inventory_delete_host", { id })),
	/**  Restores a deletion made by this running desktop process. */
	inventoryUndoDelete: (token: string) => typedError<null, Failure>(__TAURI_INVOKE("inventory_undo_delete", { token })),
	/**
	 *  Reads an OpenSSH config for the empty-inventory preview without modifying
	 *  the source file or local store.
	 */
	inventoryPreviewOpenSshConfig: (path: string) => typedError<OpenSshImportPreview, OpenSshImportError>(__TAURI_INVOKE("inventory_preview_open_ssh_config", { path })),
	/**  Imports a previously previewed OpenSSH config into an empty inventory. */
	inventoryImportOpenSshConfig: (preview: OpenSshImportPreview) => typedError<OpenSshImportResult, OpenSshImportError>(__TAURI_INVOKE("inventory_import_open_ssh_config", { preview })),
	/**
	 *  Opens the conventional `~/.ssh/config` picker used by the empty-list
	 *  onboarding flow. Cancellation returns `null`.
	 */
	chooseOpenSshConfig: () => typedError<string | null, Failure>(__TAURI_INVOKE("choose_open_ssh_config")),
	/**  Opens the native private-key file picker; `null` means cancellation. */
	chooseKeyFile: () => typedError<string | null, Failure>(__TAURI_INVOKE("choose_key_file")),
	/**  Where the local data stands. */
	localDataStatus: () => typedError<Status, LocalDataError>(__TAURI_INVOKE("local_data_status")),
	/**  Opens the store with the local passphrase. */
	unlockLocalData: (passphrase: string) => typedError<Status, LocalDataError>(__TAURI_INVOKE("unlock_local_data", { passphrase })),
	/**  On a system without a keystore, chooses the passphrase for new local data. */
	createLocalPassphrase: (passphrase: string) => typedError<Status, LocalDataError>(__TAURI_INVOKE("create_local_passphrase", { passphrase })),
	/**  Sets or changes the local passphrase. */
	setLocalPassphrase: (passphrase: string) => typedError<Status, LocalDataError>(__TAURI_INVOKE("set_local_passphrase", { passphrase })),
	/**  Removes the local passphrase, leaving the key in the keystore. */
	removeLocalPassphrase: () => typedError<Status, LocalDataError>(__TAURI_INVOKE("remove_local_passphrase")),
	/**  Keeps unreadable local data aside and starts with empty local data. */
	startWithEmptyLocalData: () => typedError<Status, LocalDataError>(__TAURI_INVOKE("start_with_empty_local_data")),
};

/** Events */
export const events = {
	sessionChanged: makeEvent<SessionChanged>("session-changed"),
	storeChanged: makeEvent<StoreChanged>("store-changed"),
};

/* Types */
/**  Input for creating or replacing an access profile. */
export type AccessProfileInput = {
	/**  Host identifier. */
	host: string,
	/**  Optional profile name. */
	name: string | null,
	/**  Remote username; it must not be empty. */
	username: string,
	/**  Credential identifier, or `null` to resolve any usable credential. */
	credential: string | null,
	/**  Route identifier, or `null` for direct access. */
	route: string | null,
	/**  Local terminal profile name. */
	terminalProfile: string | null,
	/**  Startup command. */
	startupCommand: string | null,
	/**  Agent forwarding toggle. */
	agentForwarding: boolean,
	/**  Make this the host's default profile. */
	defaultProfile: boolean,
};

/**  A standalone access profile with its host and redacted references. */
export type AccessProfileSummary = {
	/**  The profile identifier. */
	id: string,
	/**  The required host identifier. */
	host: string,
	/**  The host display name, when the host is live. */
	hostName: string | null,
	/**  Optional profile name. */
	name: string | null,
	/**  Remote username. */
	username: string,
	/**  Credential reference, with no secret material. */
	credential: CredentialLabel | null,
	/**  Credential identifier, if selected. */
	credentialId: string | null,
	/**  Route label used by the host screens. */
	route: RouteLabel,
	/**  Route identifier, or `null` for direct. */
	routeId: string | null,
	/**  Local terminal profile name. */
	terminalProfile: string | null,
	/**  Command sent after authentication, when configured. */
	startupCommand: string | null,
	/**  Whether agent forwarding is enabled. */
	agentForwarding: boolean,
	/**  Whether this is the host's default profile. */
	isDefault: boolean,
	/**  Whether one of this profile's referenced objects is missing or deleted. */
	orphaned: boolean,
	/**  Whether a later write resurrected this profile. */
	restored: boolean,
};

/**  Why adding a host failed. Nothing is saved for any variant. */
export type AddHostError =
/**  The address is empty or contains whitespace. */
{ kind: "invalidAddress" } |
/**  The port is outside the TCP range. */
{ kind: "invalidPort" } |
/**  The username is empty. */
{ kind: "emptyUsername" } |
/**  The password is empty. */
{ kind: "emptyPassword" } |
/**  The selected key file does not exist or could not be read. */
{ kind: "keyNotFound" } |
/**  The selected key file exceeds the bounded local import size. */
{ kind: "keyTooLarge" } |
/**  Reusing a private key would require scanning beyond the bounded local limit. */
{ kind: "keyReuseLimit" } |
/**  The input is not a private key. */
{ kind: "notAPrivateKey" } |
/**  Public key text was supplied where private key text is needed. */
{ kind: "publicKey" } |
/**  A PuTTY key is not accepted by the OpenSSH key reader. */
{ kind: "puttyKey" } |
/**  A disk or model operation failed. */
{ kind: "failed";
/**  A diagnostic reference safe to show for retryable failures. */
reference: string };

/**  What the interface needs to know about the running application. */
export type AppInfo = {
	/**  The application version. */
	version: string,
	/**  The platform the application runs on. */
	platform: Platform,
	/**  The interface language chosen from the system's preferences. */
	locale: Locale,
};

/**  Which parts of the inventory have content to show. */
export type Areas = {
	/**  At least one host is marked as a favorite. */
	favorites: boolean,
	/**  At least one saved session refers to a host. */
	recent: boolean,
	/**  At least one host group exists. */
	groups: boolean,
	/**  At least one credential exists. */
	keys: boolean,
	/**  At least one non-direct route is used or saved. */
	routes: boolean,
};

/**  Where a credential resolves its authentication material. */
export type CredentialBindingInput =
/**  Material is encrypted in the replicated object. */
"shared" |
/**  Material is held by each device separately. */
"device" |
/**  Material is resolved at connect time. */
"none";

/**
 *  Input for creating or replacing a credential description.
 *
 *  `secret` is accepted only for shared password/private-key credentials;
 *  `device_secret` is accepted only for device-bound password/private-key
 *  credentials. Both are consumed by the core and are not retained in any
 *  returned DTO.
 */
export type CredentialInput = {
	/**  Optional display name. */
	name: string | null,
	/**  The credential kind. */
	kind: CredentialKindInput,
	/**  Where the secret is resolved. */
	binding: CredentialBindingInput,
	/**  A shared password or private-key text. Never returned by the core. */
	secret: string | null,
	/**
	 *  Material for this device when `binding` is `device`. It is write-only
	 *  and is never returned by the core.
	 */
	deviceSecret: string | null,
	/**  Public key text for key and agent credentials. */
	publicKey: string | null,
	/**
	 *  External provider reference fields (for example `type`, `path`, and
	 *  `field`). Values are descriptions and never provider secret material.
	 */
	provider: { [key in string]: string },
	/**  Organization id for a certificate credential. */
	certificateScope: string | null,
};

/**
 *  The kind of credential exposed by the independent object editor.
 *
 *  The wire names intentionally follow the object model while keeping the
 *  private key kind readable in the interface (the host details read model
 *  calls it `key`).
 */
export type CredentialKindInput =
/**  A password stored in the encrypted shared object. */
"password" |
/**  An OpenSSH private key. */
"key" |
/**  An organization-issued certificate. */
"certificate" |
/**  A system SSH agent. */
"agent" |
/**  A hardware security key. */
"securityKey" |
/**  A non-exportable device key. */
"deviceKey" |
/**  An external credential provider. */
"external";

/**  A credential's non-secret display data. */
export type CredentialLabel = {
	/**  The credential identifier. */
	id: string,
	/**  Its kind in interface vocabulary. */
	kind: CredentialLabelKind,
	/**  The optional user-assigned name. */
	name: string | null,
	/**  The OpenSSH fingerprint, when available. */
	fingerprint: string | null,
	/**  The key comment, when available. */
	comment: string | null,
	/**  The public half of a key, when available. */
	publicKey: string | null,
};

/**  Credential kinds understood by the inventory interface. */
export type CredentialLabelKind =
/**  A password. */
"password" |
/**  A private key. */
"key" |
/**  A system SSH agent. */
"agent" |
/**  A hardware security key. */
"securityKey" |
/**  A non-exportable device key. */
"deviceKey" |
/**  An external provider. */
"external" |
/**  A short-lived certificate. */
"certificate";

/**
 *  A redacted credential object. The secret is represented only by
 *  `has_secret`; it is never returned over IPC. For a device binding this
 *  reports whether this device has local material (the replicated record does
 *  not contain that material).
 */
export type CredentialSummary = {
	/**  The credential identifier. */
	id: string,
	/**  The optional user-assigned name. */
	name: string | null,
	/**  The credential kind. */
	kind: CredentialKindInput,
	/**  The binding of its material. */
	binding: CredentialBindingInput,
	/**  Whether material is present for the selected binding; the material itself is never exposed. */
	hasSecret: boolean,
	/**  The public half of a key, when one is available. */
	publicKey: string | null,
	/**  Non-secret provider attributes. */
	provider: { [key in string]: string },
	/**  Organization scope for a certificate, when present. */
	certificateScope: string | null,
	/**  Number of access profiles that reference this credential. */
	profileCount: number,
	/**  Number of routes that reference this credential. */
	routeCount: number,
	/**  Whether a later write resurrected this credential. */
	restored: boolean,
};

/**  A deletion token returned to the interface. */
export type Deletion = {
	/**  An opaque token accepted by [`Inventory::undo_delete`]. */
	token: string,
};

/**  The editable host metadata owned by the local inventory. */
export type EditHost = {
	/**  Display name; it must not be empty. */
	name: string,
	/**  DNS name or IP literal. */
	address: string,
	/**  SSH port, validated before the object is written. */
	port: number,
	/**  Plain-text notes, or `null` to clear them. */
	notes: string | null,
	/**  Complete replacement for the tag map. */
	tags: { [key in string]: string },
	/**  Complete replacement for host-group membership. */
	groups: string[],
};

/**  Why editing host metadata failed. The host is unchanged for every variant. */
export type EditHostError =
/**  The display name is empty. */
{ kind: "emptyName" } |
/**  The address is empty or contains whitespace. */
{ kind: "invalidAddress" } |
/**  The port is outside the TCP range. */
{ kind: "invalidPort" } |
/**  Notes exceed the object-model text limit. */
{ kind: "notesTooLong" } |
/**  A tag key or value is empty or exceeds the object-model text limit. */
{ kind: "invalidTag" } |
/**  A requested group does not exist. */
{ kind: "groupNotFound" } |
/**  The local store or model failed without changing the host. */
{ kind: "failed";
/**  A diagnostic reference safe to show for retryable failures. */
reference: string };

/**  A failure that can be retried by the interface. */
export type Failure =
/**  The local store or model failed without changing the requested data. */
{ kind: "failed";
/**  A diagnostic reference safe to show for retryable failures. */
reference: string };

/**  Why creating or editing a group failed. No group is changed for failures. */
export type GroupError =
/**  The display name is empty. */
{ kind: "emptyName" } |
/**  A requested parent group does not exist. */
{ kind: "parentNotFound" } |
/**  A group cannot be its own parent. */
{ kind: "selfParent" } |
/**  The local store or model failed without changing the group. */
{ kind: "failed";
/**  A diagnostic reference safe to show for retryable failures. */
reference: string };

/**  Input for creating or editing a host group. */
export type GroupInput = {
	/**  Display name; it must not be empty. */
	name: string,
	/**  Optional parent group. */
	parent: string | null,
};

/**  A host group in the sidebar. */
export type GroupSummary = {
	/**  The group identifier. */
	id: string,
	/**  Display name. */
	name: string,
	/**  Parent group, if nested. */
	parent: string | null,
	/**  Number of live hosts in the group. */
	hostCount: number,
};

/**  Details shown beside the host list. */
export type HostDetails = {
	/**  Plain-text notes. */
	notes: string | null,
	/**  All logins for this host. */
	logins: LoginSummary[],
} & HostSummary;

/**  Which hosts to list. */
export type HostSource =
/**  Every live host. */
{ kind: "all" } |
/**  Hosts marked as favorites. */
{ kind: "favorites" } |
/**  Hosts referenced by recent sessions. */
{ kind: "recent" } |
/**  Hosts in one group. */
{ kind: "group";
/**  The group identifier. */
id: string };

/**  A row in the host list. */
export type HostSummary = {
	/**  The host identifier. */
	id: string,
	/**  Display name. */
	name: string,
	/**  DNS name or IP literal. */
	address: string,
	/**  SSH port. */
	port: number,
	/**  The default login's username. */
	username: string | null,
	/**  Number of logins for this host. */
	loginCount: number,
	/**  How its default login connects. */
	route: RouteLabel,
	/**  Whether it is a favorite. */
	favorite: boolean,
	/**  User tags. */
	tags: { [key in string]: string },
	/**  Group identifiers. */
	groups: string[],
	/**  Whether a later write resurrected it after deletion. */
	restored: boolean,
};

/**  A failure of an operation on the local data, as shown to the user. */
export type LocalDataError =
/**  The passphrase is not correct. Nothing changed. */
{ kind: "wrongPassphrase" } |
/**  The passphrase is empty. Nothing changed. */
{ kind: "emptyPassphrase" } |
/**  The passphrase cannot be removed without a keystore. Nothing changed. */
{ kind: "passphraseRequired" } |
/**
 *  The operation needs the store to be in another state, for example
 *  unlocked. Nothing changed.
 */
{ kind: "invalidState" } |
/**  The platform or the disk failed. Nothing changed. */
{ kind: "failed";
/**  A diagnostic reference for support, free of secrets. */
reference: string };

/**
 *  A language the interface is written in (`11-client-architecture.md` §4).
 *
 *  English is the source language; every other language is written from it.
 */
export type Locale =
/**  English, the source language. */
"en" |
/**  Simplified Chinese. */
"zh-Hans";

/**  One login shown in host details. */
export type LoginSummary = {
	/**  The access profile identifier. */
	id: string,
	/**  Optional display name. */
	name: string | null,
	/**  Remote username. */
	username: string,
	/**  Its non-secret credential, if one is selected. */
	credential: CredentialLabel | null,
	/**  How this login reaches its host. */
	route: RouteLabel,
	/**  Whether it is the host's default login. */
	isDefault: boolean,
};

/**  Input for the tier-0 add-host flow. */
export type NewHost = {
	/**  Display name; defaults to the address. */
	name: string | null,
	/**  DNS name or IP literal. */
	address: string,
	/**  SSH port; defaults to 22. */
	port: number | null,
	/**  Remote username. */
	username: string,
	/**  Authentication material. */
	signIn: SignIn,
};

/**
 *  Why an independent object edit failed. No operation writes anything for a
 *  validation error, and references are checked before a write begins.
 */
export type ObjectEditError =
/**  One of the supplied identifiers is not a UUID. */
{ kind: "invalidId"; field: string } |
/**  A referenced or edited object does not exist. */
{ kind: "notFound"; entity: string } |
/**  A required name is empty. */
{ kind: "emptyName" } |
/**  A required username is empty. */
{ kind: "emptyUsername" } |
/**  A text field exceeds the object-model limit. */
{ kind: "textTooLong"; field: string } |
/**  A profile references a credential of the wrong type or a missing one. */
{ kind: "invalidCredential" } |
/**  A profile or route references a missing route/profile/host. */
{ kind: "invalidRoute" } |
/**  A proxy is not a valid host:port endpoint. */
{ kind: "invalidProxy" } |
/**  A route command is empty or exceeds the model limit. */
{ kind: "invalidCommand" } |
/**  Kind and binding do not satisfy the object model. */
{ kind: "invalidCredentialBinding" } |
/**  Shared password/private-key credentials require material on creation. */
{ kind: "secretRequired" } |
/**  A secret was supplied to a binding that must never store one. */
{ kind: "secretNotAllowed" } |
/**  A route or credential is still referenced by another object. */
{ kind: "inUse" } |
/**  A default profile cannot be deleted until another profile is selected. */
{ kind: "defaultProfile" } |
/**  Managed routes are organization-authored and unavailable locally. */
{ kind: "managedRoute" } |
/**  The local store or model failed without changing the requested object. */
{ kind: "failed"; reference: string };

/**
 *  A representable entry found in an OpenSSH configuration file. This is a
 *  preview DTO: it never contains private key material.
 */
export type OpenSshImportEntry = {
	/**  The `Host` alias that becomes the display name. */
	alias: string,
	/**  The resolved host name or address. */
	address: string,
	/**  SSH port, defaulting to 22. */
	port: number,
	/**  The configured user, or the current local user when omitted. */
	username: string,
	/**  An identity file to read at commit time, if configured. */
	identityFile: string | null,
};

/**  Why the empty-list OpenSSH import could not proceed. */
export type OpenSshImportError =
/**  The selected file could not be read. */
{ kind: "fileNotFound" } |
/**  The source was not valid UTF-8. */
{ kind: "notText" } |
/**  The config or its simple-host list exceeds the bounded onboarding import. */
{ kind: "tooLarge" } |
/**  No representable host block was found. */
{ kind: "noHosts" } |
/**  The source changed after the user reviewed its preview. */
{ kind: "sourceChanged" } |
/**  Import is intentionally limited to the first-launch empty inventory. */
{ kind: "inventoryNotEmpty" } |
/**  An identity file named by a representable entry could not be read. */
{ kind: "identityNotFound";
/**  The path, which is not secret. */
path: string } |
/**  The selected file or local store failed without a partial import. */
{ kind: "failed";
/**  A diagnostic reference safe to show for retryable failures. */
reference: string };

/**  A preview of importing one OpenSSH configuration file. */
export type OpenSshImportPreview = {
	/**  The selected source path. */
	path: string,
	/**  Entries that can be represented by the tier-0 importer. */
	entries: OpenSshImportEntry[],
	/**  Literal aliases excluded from import, with a visible reason. */
	skippedHosts: OpenSshSkippedHost[],
	/**  Directives that will be skipped and shown to the user. */
	unsupported: OpenSshUnsupportedDirective[],
};

/**  The result of importing a preview into an empty inventory. */
export type OpenSshImportResult = {
	/**  Hosts created from the preview. */
	hosts: HostDetails[],
	/**  Literal aliases excluded from import, with a visible reason. */
	skippedHosts: OpenSshSkippedHost[],
	/**  Unsupported directives retained for the report. */
	unsupported: OpenSshUnsupportedDirective[],
};

/**  Why a literal `Host` alias cannot be imported without changing its meaning. */
export type OpenSshSkipReason =
/**  A directive within this host block has no tier-0 representation. */
{ kind: "unsupportedDirective";
/**  The directive name as written. */
directive: string } |
/**  A global rule could change any host in the source file. */
{ kind: "globalRules";
/**  The global directive responsible for the exclusion. */
directive: string } |
/**  Multiple `Host` blocks name the same alias. */
{ kind: "duplicateAlias" } |
/**  A supported directive has a value outside the simple import subset. */
{ kind: "invalidValue";
/**  The directive name as written. */
directive: string };

/**  A literal alias excluded from the tier-0 import preview. */
export type OpenSshSkippedHost = {
	/**  The `Host` alias. */
	alias: string,
	/**  One-based line of its `Host` block. */
	line: number,
	/**  Why importing it would be misleading. */
	reason: OpenSshSkipReason,
};

/**  A directive the limited tier-0 importer cannot represent yet. */
export type OpenSshUnsupportedDirective = {
	/**  One-based source line. */
	line: number,
	/**  The directive name as written. */
	directive: string,
};

/**  The desktop platform the application runs on. */
export type Platform =
/**  macOS. */
"macos" |
/**  Windows. */
"windows" |
/**  Any other system; Phase 1 ships only macOS and Windows builds. */
"other";

/**  How the local database key is protected. */
export type Protection =
/**  The platform keystore alone. */
"keystore" |
/**  The platform keystore and a local passphrase. */
"keystoreAndPassphrase" |
/**  A local passphrase alone, on a platform without a keystore. */
"passphraseOnly";

/**
 *  A redacted entry in the device-local Recent session history.
 *  This is intentionally a read model. It carries no credential or terminal
 *  data, and recording or reconnecting a session remains the responsibility of
 *  the connection and session managers.
 */
export type RecentSession = {
	/**  The device-local session identifier. */
	id: string,
	/**  The live Host this session used. */
	hostId: string,
	/**  The Host display name at read time. */
	hostName: string,
	/**  The Host DNS name or IP literal. */
	address: string,
	/**  The Host SSH port. */
	port: number,
	/**  The login username used by the session. */
	username: string,
	/**  The session kind. */
	kind: RecentSessionKind,
	/**
	 *  Start time in Unix milliseconds, encoded as decimal text at the IPC
	 *  boundary so JavaScript cannot lose precision.
	 */
	startedAt: string,
	/**  End time in Unix milliseconds, if it has ended. */
	endedAt: string | null,
	/**  End status, if it has ended. */
	outcome: RecentSessionOutcome | null,
};

/**  The kind of a device-local session shown in the Recent area. */
export type RecentSessionKind = "terminal" | "files" | "forward";

/**  How a device-local session ended, when it is no longer open. */
export type RecentSessionOutcome = "closed" | "failed";

/**  The type of a changed object, in the frontend's terms. */
export type RecordType =
/**  A host. */
"host" |
/**  A login. */
"accessProfile" |
/**  A key, password, or other credential. */
"credential" |
/**  A jump route or proxy. */
"route" |
/**  A group. */
"hostGroup" |
/**  A known host key. */
"trustRecord" |
/**  A snippet. */
"snippet" |
/**  A tunnel. */
"forward" |
/**  A workspace. */
"workspace" |
/**  A preference. */
"preference" |
/**  A network reached through the bastion. */
"gatewayNetwork" |
/**  A type a newer version of Scoplen defines. */
"unknown";

/**
 *  A device-independent route definition. Managed routes are represented so
 *  that they can be displayed, but local editing rejects them until the
 *  organization client is available.
 */
export type RouteDefinition =
/**  Ordered access profiles used as jump hosts. */
{ kind: "jump"; hops: string[] } |
/**  A SOCKS5 proxy at `host:port`. */
{ kind: "socks5"; proxy: string; credential: string | null } |
/**  An HTTP CONNECT proxy at `host:port`. */
{ kind: "httpConnect"; proxy: string; credential: string | null } |
/**  A local OpenSSH `ProxyCommand`. */
{ kind: "command"; command: string } |
/**  A managed gateway network, authored by the organization. */
{ kind: "managed"; gatewayNetwork: string };

/**  Input for creating or replacing a Route. */
export type RouteInput = {
	/**  Display name; it must not be empty. */
	name: string,
	/**  Route-specific definition. */
	definition: RouteDefinition,
};

/**  How a login reaches its host. */
export type RouteLabel =
/**  A direct SSH connection. */
{ kind: "direct" } |
/**  Through one or more jump hosts. */
{ kind: "jump";
/**  The route name. */
name: string } |
/**  Through a SOCKS or HTTP proxy. */
{ kind: "proxy";
/**  The route name. */
name: string } |
/**  Through a ProxyCommand. */
{ kind: "command";
/**  The route name. */
name: string } |
/**  Through a managed gateway network. */
{ kind: "bastion";
/**  The route name. */
name: string };

/**  A redacted Route object. */
export type RouteSummary = {
	/**  The route identifier. */
	id: string,
	/**  Display name. */
	name: string,
	/**  Route-specific definition. */
	definition: RouteDefinition,
	/**  Number of access profiles that reference this route. */
	profileCount: number,
	/**  Whether a jump profile or proxy credential is missing. */
	orphaned: boolean,
	/**  Whether a later write resurrected this route. */
	restored: boolean,
};

/**  Why a device-local session view should reload. */
export type SessionChangeKind =
/**  A connection owner recorded that a transport opened. */
"opened" |
/**  A connection owner recorded a terminal outcome. */
"closed" |
/**  The user removed an ended session from local history. */
"forgotten";

/**
 *  A device-local session lifecycle event; session history is not a replicated
 *  object and therefore has its own event instead of `StoreChanged`.
 */
export type SessionChanged = {
	/**  The session identifier. */
	sessionId: string,
	/**  The lifecycle transition. */
	change: SessionChangeKind,
};

/**  Why a device-local session event could not be applied. */
export type SessionError =
/**  The profile identifier was not a UUID. */
{ kind: "invalidProfileId" } |
/**  The session identifier was not a UUID. */
{ kind: "invalidSessionId" } |
/**  The login no longer exists on this device. */
{ kind: "profileNotFound" } |
/**  The session no longer exists in local history. */
{ kind: "sessionNotFound" } |
/**  The session already has an ending outcome. */
{ kind: "alreadyClosed" } |
/**  A live session must report an outcome before it can be forgotten. */
{ kind: "activeSession" } |
/**  The connection engine has not been connected to this history service. */
{ kind: "transportUnavailable" } |
/**  The local store failed without exposing its internals or secrets. */
{ kind: "failed";
/**  A diagnostic reference safe to show for retryable failures. */
reference: string };

/**  How a new host authenticates. */
export type SignIn =
/**  Store a password in the encrypted personal object. */
{ kind: "password";
/**  The password to store in the encrypted local object. */
password: string } |
/**  Read an OpenSSH private key from a path. */
{ kind: "keyFile";
/**  The path to an OpenSSH private key file. */
path: string } |
/**  Use OpenSSH private-key text supplied by the user. */
{ kind: "keyText";
/**  OpenSSH private-key text. */
key: string } |
/**  Generate a key (reserved for the key-generation flow). */
{ kind: "generateKey" } |
/**  Resolve a key from the system agent. */
{ kind: "agent" };

/**  Whether the local data can be used, and if not, what is needed. */
export type Status =
/**  The store is open. */
{ state: "open";
/**  How its key is protected. */
protection: Protection } |
/**  The user must enter the local passphrase. */
{ state: "needsPassphrase";
/**  How the key is protected. */
protection: Protection } |
/**  First launch without a keystore: the user must choose a passphrase. */
{ state: "needsNewPassphrase" } |
/**  The store exists but cannot be opened on this device. */
{ state: "unreadable";
/**  Why. */
reason: UnreadableReason };

/**
 *  Objects in the local store changed; views showing them should reload.
 *  Sent after the change is committed.
 */
export type StoreChanged = {
	/**  The type of the changed objects. */
	recordType: RecordType,
	/**  Their identifiers, as lowercase hyphenated UUIDs. */
	ids: string[],
};

/**  Why the local store cannot be opened. */
export type UnreadableReason =
/**  Its key is missing from the keystore. */
"keyMissing" |
/**  The key does not decrypt it. */
"wrongKey" |
/**  It was written by a newer version of Scoplen. */
"newerVersion";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

