// SPDX-License-Identifier: Apache-2.0
// Generated from src-tauri by `pnpm bindings`. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns the application version, platform, and interface language. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Called by the frontend once its first screen has rendered. */
	shellReady: () => __TAURI_INVOKE<void>("shell_ready"),
	/**  Where the local data stands. */
	localDataStatus: () => typedError<Status, LocalDataError>(__TAURI_INVOKE("local_data_status")),
	/**  Opens the store with the local passphrase. */
	unlockLocalData: (passphrase: string) => typedError<Status, LocalDataError>(__TAURI_INVOKE("unlock_local_data", { passphrase })),
	/**  On a system without a keystore, chooses the passphrase for new local data. */
	createLocalPassphrase: (passphrase: string) => typedError<Status, LocalDataError>(__TAURI_INVOKE("create_local_passphrase", { passphrase })),
	/**  Sets or changes the local passphrase. */
	setLocalPassphrase: (passphrase: string) => typedError<Status, LocalDataError>(__TAURI_INVOKE("set_local_passphrase", { passphrase })),
	/**  Removes the local passphrase, leaving the key in the keystore. */
	removeLocalPassphrase: () => typedError<Status, LocalDataError>(__TAURI_INVOKE("remove_local_passphrase")),
	/**  Keeps unreadable local data aside and starts with empty local data. */
	startWithEmptyLocalData: () => typedError<Status, LocalDataError>(__TAURI_INVOKE("start_with_empty_local_data")),
};

/** Events */
export const events = {
	storeChanged: makeEvent<StoreChanged>("store-changed"),
};

/* Types */
/**  What the interface needs to know about the running application. */
export type AppInfo = {
	/**  The application version. */
	version: string,
	/**  The platform the application runs on. */
	platform: Platform,
	/**  The interface language chosen from the system's preferences. */
	locale: Locale,
};

/**  A failure of an operation on the local data, as shown to the user. */
export type LocalDataError = 
/**  The passphrase is not correct. Nothing changed. */
{ kind: "wrongPassphrase" } | 
/**  The passphrase is empty. Nothing changed. */
{ kind: "emptyPassphrase" } | 
/**  The passphrase cannot be removed without a keystore. Nothing changed. */
{ kind: "passphraseRequired" } | 
/**
 *  The operation needs the store to be in another state, for example
 *  unlocked. Nothing changed.
 */
{ kind: "invalidState" } | 
/**  The platform or the disk failed. Nothing changed. */
{ kind: "failed"; 
/**  A diagnostic reference for support, free of secrets. */
reference: string };

/**
 *  A language the interface is written in (`11-client-architecture.md` §4).
 * 
 *  English is the source language; every other language is written from it.
 */
export type Locale = 
/**  English, the source language. */
"en" | 
/**  Simplified Chinese. */
"zh-Hans";

/**  The desktop platform the application runs on. */
export type Platform = 
/**  macOS. */
"macos" | 
/**  Windows. */
"windows" | 
/**  Any other system; Phase 1 ships only macOS and Windows builds. */
"other";

/**  How the local database key is protected. */
export type Protection = 
/**  The platform keystore alone. */
"keystore" | 
/**  The platform keystore and a local passphrase. */
"keystoreAndPassphrase" | 
/**  A local passphrase alone, on a platform without a keystore. */
"passphraseOnly";

/**  The type of a changed object, in the frontend's terms. */
export type RecordType = 
/**  A host. */
"host" | 
/**  A login. */
"accessProfile" | 
/**  A key, password, or other credential. */
"credential" | 
/**  A jump route or proxy. */
"route" | 
/**  A group. */
"hostGroup" | 
/**  A known host key. */
"trustRecord" | 
/**  A snippet. */
"snippet" | 
/**  A tunnel. */
"forward" | 
/**  A workspace. */
"workspace" | 
/**  A preference. */
"preference" | 
/**  A network reached through the bastion. */
"gatewayNetwork" | 
/**  A type a newer version of Scoplen defines. */
"unknown";

/**  Whether the local data can be used, and if not, what is needed. */
export type Status = 
/**  The store is open. */
{ state: "open"; 
/**  How its key is protected. */
protection: Protection } | 
/**  The user must enter the local passphrase. */
{ state: "needsPassphrase"; 
/**  How the key is protected. */
protection: Protection } | 
/**  First launch without a keystore: the user must choose a passphrase. */
{ state: "needsNewPassphrase" } | 
/**  The store exists but cannot be opened on this device. */
{ state: "unreadable"; 
/**  Why. */
reason: UnreadableReason };

/**
 *  Objects in the local store changed; views showing them should reload.
 *  Sent after the change is committed.
 */
export type StoreChanged = {
	/**  The type of the changed objects. */
	recordType: RecordType,
	/**  Their identifiers, as lowercase hyphenated UUIDs. */
	ids: string[],
};

/**  Why the local store cannot be opened. */
export type UnreadableReason = 
/**  Its key is missing from the keystore. */
"keyMissing" | 
/**  The key does not decrypt it. */
"wrongKey" | 
/**  It was written by a newer version of Scoplen. */
"newerVersion";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

