// SPDX-License-Identifier: Apache-2.0

//! Device credential storage and capability discovery.
//!
//! The platform keystore protects the private scalar at rest. The scalar is
//! returned only to the Rust connection boundary when a signer is needed; it
//! is never exposed through the frontend or persisted in a replicated object.
//! Hardware-backed signing and FIDO2 discovery remain explicit capabilities,
//! so unsupported machines fail closed instead of silently using a software
//! substitute.

use std::path::Path;

use base64::{Engine as _, engine::general_purpose::STANDARD};
use getrandom::fill as random_fill;
use p256::ecdsa::SigningKey;
use uuid::Uuid;
use zeroize::Zeroizing;

use crate::keystore::{KeystoreError, credential_key_store};

const HANDLE_PREFIX: &str = "device-keystore-v1:";

/// A device key identity created in the platform keystore.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DeviceKeyIdentity {
    /// The opaque handle persisted in the device-local credential table.
    pub handle: String,
    /// The OpenSSH public key corresponding to the private key.
    pub public_key: String,
}

/// A resolved device key. The private scalar is zeroized when dropped.
#[derive(Debug)]
pub struct ResolvedDeviceKey {
    /// The private P-256 scalar for the connection signer.
    pub secret: Zeroizing<Vec<u8>>,
}

/// Security-key support available from this build and machine.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SecurityKeyCapability {
    /// FIDO2/WebAuthn integration is not linked in this build.
    Unsupported,
}

/// A platform credential operation failed.
#[derive(Debug, thiserror::Error)]
pub enum CredentialError {
    /// The supplied handle is not a handle generated by this module.
    #[error("the device credential handle is invalid")]
    InvalidHandle,
    /// The platform keystore is not available on this operating system.
    #[error("this platform has no device credential keystore")]
    Unsupported,
    /// The underlying keystore failed.
    #[error(transparent)]
    Keystore(#[from] KeystoreError),
    /// The operating system random source failed.
    #[error("the operating system random source failed: {0}")]
    Random(String),
    /// The generated scalar was not a valid P-256 key.
    #[error("the platform generated an invalid device key")]
    InvalidKey,
}

/// Returns the security-key capability without probing or prompting hardware.
#[must_use]
pub const fn security_key_capability() -> SecurityKeyCapability {
    // libfido2/WebAuthn is intentionally not claimed until its user-presence
    // and cancellation boundary is implemented in the platform crate.
    SecurityKeyCapability::Unsupported
}

/// Create a P-256 device key and protect it in the platform keystore.
pub fn create_device_key(
    data_dir: &Path,
    credential: Uuid,
) -> Result<DeviceKeyIdentity, CredentialError> {
    let Some(slot) = credential_key_store(data_dir, credential) else {
        return Err(CredentialError::Unsupported);
    };
    let secret = generate_scalar()?;
    let key = signing_key(&secret)?;
    slot.store(&secret)?;
    Ok(DeviceKeyIdentity { handle: handle(credential), public_key: openssh_public_key(&key) })
}

/// Resolve a previously created device key from the platform keystore.
pub fn resolve_device_key(
    data_dir: &Path,
    credential: Uuid,
    stored_handle: &str,
) -> Result<ResolvedDeviceKey, CredentialError> {
    if stored_handle != handle(credential) {
        return Err(CredentialError::InvalidHandle);
    }
    let Some(slot) = credential_key_store(data_dir, credential) else {
        return Err(CredentialError::Unsupported);
    };
    let secret = slot.load()?.ok_or(CredentialError::InvalidHandle)?;
    let _ = signing_key(&secret)?;
    Ok(ResolvedDeviceKey { secret })
}

/// Remove a device key from the platform keystore.
pub fn delete_device_key(
    data_dir: &Path,
    credential: Uuid,
    stored_handle: &str,
) -> Result<(), CredentialError> {
    if stored_handle != handle(credential) {
        return Err(CredentialError::InvalidHandle);
    }
    let Some(slot) = credential_key_store(data_dir, credential) else {
        return Err(CredentialError::Unsupported);
    };
    slot.delete()?;
    Ok(())
}

fn handle(credential: Uuid) -> String {
    format!("{HANDLE_PREFIX}{credential}")
}

fn generate_scalar() -> Result<Zeroizing<Vec<u8>>, CredentialError> {
    for _ in 0..8 {
        let mut bytes = Zeroizing::new(vec![0u8; 32]);
        random_fill(&mut bytes).map_err(|error| CredentialError::Random(error.to_string()))?;
        if signing_key(&bytes).is_ok() {
            return Ok(bytes);
        }
    }
    Err(CredentialError::InvalidKey)
}

fn signing_key(secret: &[u8]) -> Result<SigningKey, CredentialError> {
    let scalar: &[u8; 32] = secret.try_into().map_err(|_| CredentialError::InvalidKey)?;
    SigningKey::from_bytes(scalar.into()).map_err(|_| CredentialError::InvalidKey)
}

fn openssh_public_key(key: &SigningKey) -> String {
    let point = key.verifying_key().to_encoded_point(false);
    let mut blob = Vec::with_capacity(19 + point.as_bytes().len());
    put_string(&mut blob, b"ecdsa-sha2-nistp256");
    put_string(&mut blob, b"nistp256");
    put_string(&mut blob, point.as_bytes());
    format!("ecdsa-sha2-nistp256 {}", STANDARD.encode(blob))
}

fn put_string(output: &mut Vec<u8>, value: &[u8]) {
    output.extend_from_slice(&(value.len() as u32).to_be_bytes());
    output.extend_from_slice(value);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn handles_are_bound_to_the_credential_id() {
        let credential = Uuid::from_u128(7);
        let handle = super::handle(credential);
        assert!(handle.starts_with(HANDLE_PREFIX));
        assert_ne!(handle, super::handle(Uuid::from_u128(8)));
    }

    #[test]
    fn security_key_support_is_explicitly_unavailable() {
        assert_eq!(security_key_capability(), SecurityKeyCapability::Unsupported);
    }

    #[cfg(any(target_os = "macos", windows))]
    #[test]
    fn device_key_round_trip_uses_a_keystore_slot() {
        let dir = tempfile::tempdir().unwrap();
        let credential = Uuid::from_u128(9);
        let identity = create_device_key(dir.path(), credential).unwrap();
        assert!(identity.public_key.starts_with("ecdsa-sha2-nistp256 "));
        let resolved = resolve_device_key(dir.path(), credential, &identity.handle).unwrap();
        assert_eq!(resolved.secret.len(), 32);
        delete_device_key(dir.path(), credential, &identity.handle).unwrap();
        assert!(matches!(
            resolve_device_key(dir.path(), credential, &identity.handle),
            Err(CredentialError::InvalidHandle)
        ));
    }

    #[test]
    fn malformed_handles_fail_before_touching_the_keystore() {
        let dir = tempfile::tempdir().unwrap();
        let result = resolve_device_key(dir.path(), Uuid::from_u128(1), "not-a-handle");
        assert!(matches!(result, Err(CredentialError::InvalidHandle)));
    }
}
